# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdBKBczzGEN6rbAE7_LKFYMdEflwAKkY
"""

import streamlit as st
import numpy as np
import joblib

# =========================
# Konfigurasi Halaman
# =========================
st.set_page_config(
    page_title="Simulator Risiko Mesin",
    page_icon="🤎",
    layout="centered"
)

# =========================
# CSS Tema Brown Cream
# =========================
st.markdown("""
<style>

.stApp{
    background-color:#F8F3EC;
}

h1,h2,h3{
    color:#5C4033;
    text-align:center;
}

p{
    color:#6F5E53;
}

div[data-testid="stNumberInput"] label{
    color:#5C4033;
    font-weight:bold;
}

div.stButton > button{
    background-color:#8B6B4A;
    color:white;
    border-radius:12px;
    border:none;
    width:100%;
    height:50px;
    font-size:18px;
    font-weight:bold;
}

div.stButton > button:hover{
    background-color:#6F4E37;
    color:white;
}

[data-testid="stMetric"]{
    background:#FFF8EE;
    border-radius:15px;
    padding:10px;
}

</style>
""", unsafe_allow_html=True)

# =========================
# Load Model
# =========================
loaded_model = joblib.load("model_risiko_v1.joblib")
loaded_scaler = joblib.load("scaler_risiko_v1.joblib")

# =========================
# Judul
# =========================
st.title("🤎 Simulator Risiko Kegagalan Sistem")

st.write(
    "Masukkan kondisi sensor mesin untuk mengetahui skor risiko kegagalan sistem."
)

st.divider()

# =========================
# Input
# =========================
suhu = st.number_input(
    "🌡 Suhu Mesin",
    min_value=0.0,
    value=85.0
)

getaran = st.number_input(
    "⚙ Getaran Mesin",
    min_value=0.0,
    value=7.0
)

# =========================
# Prediksi
# =========================
if st.button("✨ Simulasikan Risiko"):

    data_baru = np.array([[suhu, getaran]])

    data_scaled = loaded_scaler.transform(data_baru)

    hasil = loaded_model.predict(data_scaled)

    st.success(f"### Skor Risiko : {hasil[0]:.2f}")

    if suhu > 120 or suhu < 10:
        st.warning(
            "⚠ Input berada di luar jangkauan data latihan.\n"
            "Hasil simulasi mungkin tidak akurat."
        )
    else:
        st.info("✅ Sistem Stabil. Data masih sesuai dengan data latihan.")